from __future__ import annotations

import re
from typing import Any

from agent.client import MCPClient


class MCPPlanningRunner:
    """
    Executes individual planning tasks through the existing MCP client.

    The runner exposes only explicit, safe MCP operations.
    It never executes arbitrary Python code generated by the LLM.
    """

    def __init__(self, mcp_client: MCPClient | None = None):
        self.mcp = mcp_client or MCPClient()

    # ========================================================
    # Execute one planning task
    # ========================================================

    async def execute_task(
        self,
        instruction: str,
        previous_outputs: dict[str, str] | None = None,
    ) -> str:
        """
        Map a planning instruction to an allowed MCP operation.

        If the instruction is a reasoning task rather than a direct
        MCP retrieval operation, return the available evidence so
        the caller can perform the reasoning/synthesis step.
        """

        text = instruction.lower().strip()

        previous_outputs = previous_outputs or {}

        # ----------------------------------------------------
        # Search all open tickets
        # ----------------------------------------------------

        if (
            "open" in text
            and "ticket" in text
            and (
                "find" in text
                or "search" in text
                or "list" in text
                or "retrieve" in text
                or "get" in text
            )
        ):
            result = await self.mcp.search_open_tickets()

            return str(result)

        # ----------------------------------------------------
        # Search by team
        # ----------------------------------------------------

        teams = [
            "backend",
            "frontend",
            "support",
            "product",
        ]

        for team in teams:

            if (
                team in text
                and (
                    "team" in text
                    or "assigned" in text
                )
            ):
                result = await self.mcp.search_by_team(team)

                return str(result)

        # ----------------------------------------------------
        # Get a specific ticket
        # ----------------------------------------------------

        ticket_match = re.search(
            r"(?:ticket\s*(?:id|#)?|ticket\s+number)\s*[:#]?\s*(\d+)",
            text,
            flags=re.IGNORECASE,
        )

        if ticket_match:

            ticket_id = int(
                ticket_match.group(1)
            )

            result = await self.mcp.get_ticket(
                ticket_id
            )

            return str(result)

        # ----------------------------------------------------
        # Dashboard
        # ----------------------------------------------------

        if "dashboard" in text:

            result = await self.mcp.get_dashboard()

            return str(result)

        # ----------------------------------------------------
        # Report
        # ----------------------------------------------------

        if (
            "report" in text
            or "generate report" in text
        ):

            result = await self.mcp.generate_report()

            return str(result)

        # ----------------------------------------------------
        # Knowledge / Policy search
        # ----------------------------------------------------

        if (
            "policy" in text
            or "sla" in text
            or "security" in text
            or "knowledge" in text
        ):

            result = await self.mcp.decompose_and_search(
                instruction,
                top_k=3,
            )

            return str(result)

        # ----------------------------------------------------
        # Reasoning task
        # ----------------------------------------------------

        if previous_outputs:

            evidence = "\n\n".join(
                f"{task_id}:\n{output}"
                for task_id, output
                in previous_outputs.items()
            )

            return (
                "REASONING TASK\n\n"
                f"Instruction:\n{instruction}\n\n"
                f"Available evidence:\n{evidence}"
            )

        # ----------------------------------------------------
        # No MCP operation matched
        # ----------------------------------------------------

        return (
            "REASONING TASK\n\n"
            f"Instruction:\n{instruction}\n\n"
            "No MCP retrieval operation was required."
        )

    # ========================================================
    # Execute complete static planning workflow
    # ========================================================

    async def run(
        self,
        goal: str,
    ) -> dict[str, Any]:
        """
        Execute the decomposition-first planning workflow.

        This method is kept for compatibility with the static
        planning implementation.
        """

        if not goal or not goal.strip():
            raise ValueError(
                "Planning goal cannot be empty."
            )

        from planning.executor import run_planning

        return await run_planning(
            goal=goal.strip(),
            mcp_client=self.mcp,
        )