from __future__ import annotations

import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Callable

from langchain_core.language_models.chat_models import BaseChatModel
from pydantic import BaseModel, ConfigDict

from planning.models import Plan


PLANNER_SYSTEM = """
You are a careful task-decomposition planner for a support-ticket
management system.

Your job is to convert a complex user request into a small executable DAG.

Rules:

1. Produce 3-6 concrete tasks.
2. Every task must contribute directly to the user's goal.
3. Tasks that can be performed independently should be parallel.
4. Dependencies must refer only to task IDs in the plan.
5. The final task must synthesize the results of the necessary previous tasks.
6. Do not invent ticket data, policies, or facts.
7. When the request requires ticket information, create tasks that retrieve or
   analyze that information rather than guessing it.
8. Use short IDs such as t1, t2, t3.
9. Prefer the real support-ticket operations available through the MCP server.
10. Do not claim that a ticket was retrieved or updated unless the corresponding
    MCP operation was actually executed.
"""


class PlannedTask(BaseModel):
    """
    Intermediate task schema returned by the LLM planner.
    """

    model_config = ConfigDict(extra="forbid")

    id: str
    instruction: str
    depends_on: list[str] = []


class GeneratedPlan(BaseModel):
    """
    Raw plan generated by the LLM.
    """

    model_config = ConfigDict(extra="forbid")

    goal: str
    tasks: list[PlannedTask]


def decompose_goal(
    goal: str,
    llm: BaseChatModel,
) -> Plan:
    """
    Convert a complex support-ticket request into a validated DAG.

    The LLM creates the initial plan while the Plan model performs
    deterministic validation of IDs, dependencies, and cycles.
    """

    generated = llm.with_structured_output(
        GeneratedPlan,
        method="json_schema",
    ).invoke(
        [
            ("system", PLANNER_SYSTEM),
            (
                "human",
                f"""
Decompose the following support-ticket request into 3-6 executable tasks.

User goal:
{goal!r}

Requirements:

- Preserve the supplied goal exactly in the goal field.
- Use task IDs such as t1, t2, t3.
- Use dependencies to represent the correct execution order.
- End with exactly one final synthesis task.
- Retrieval tasks should explicitly mention the MCP operation they require.
- Do not invent ticket IDs, ticket status, priority, team names, or other
  database facts.

Available support-ticket MCP operations include:

- get_ticket(ticket_id)
- search_open_tickets()
- search_by_team(team_name)
- update_ticket_status(ticket_id, status)

The plan must describe what needs to be done.
Do not execute the tools yourself.
""",
            ),
        ],
        temperature=0.1,
    )

    payload = generated.model_dump()

    # The user's original request is authoritative.
    payload["goal"] = goal

    return Plan.model_validate(payload)


def _find_ticket_id(text: str) -> int | None:
    """
    Extract a ticket ID from a task instruction when one is explicitly present.

    Supported examples:
        ticket 5
        ticket #5
        ticket id 5
        ticket id: 5
        Ticket ID: 5
    """

    patterns = [
        r"\bticket\s*#?\s*(\d+)\b",
        r"\bticket\s+id\s*[:=#]?\s*(\d+)\b",
    ]

    for pattern in patterns:
        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE,
        )

        if match:
            return int(match.group(1))

    return None


def _find_team_name(text: str) -> str | None:
    """
    Extract a team name when the task explicitly refers to one.

    This is intentionally conservative.
    """

    match = re.search(
        r"(?:team|assigned\s+to)\s*[:=]?\s*([A-Za-z][A-Za-z0-9 _-]*)",
        text,
        flags=re.IGNORECASE,
    )

    if not match:
        return None

    return match.group(1).strip().rstrip(".")


def execute_mcp_task(
    instruction: str,
    mcp_tools: dict[str, Callable[..., Any]],
) -> str | None:
    """
    Execute a task through a real Support-Ticket MCP operation
    when the instruction clearly maps to a supported operation.

    Returns:
        String result when an MCP operation was executed.
        None when the task is reasoning/synthesis.
    """

    normalized = instruction.lower()

    # =========================================================
    # Search all open tickets
    # =========================================================

    if (
        "search open tickets" in normalized
        or "find all open tickets" in normalized
        or "retrieve all open tickets" in normalized
        or "get all open tickets" in normalized
        or "find the open tickets" in normalized
    ):
        tool = mcp_tools.get("search_open_tickets")

        if tool is None:
            raise RuntimeError(
                "MCP tool 'search_open_tickets' was not provided."
            )

        result = tool()

        return str(result)

    # =========================================================
    # Get a specific ticket
    # =========================================================

    if (
        "get ticket" in normalized
        or "retrieve ticket" in normalized
        or "inspect ticket" in normalized
        or "look up ticket" in normalized
    ):
        ticket_id = _find_ticket_id(instruction)

        if ticket_id is None:
            return None

        tool = mcp_tools.get("get_ticket")

        if tool is None:
            raise RuntimeError(
                "MCP tool 'get_ticket' was not provided."
            )

        result = tool(ticket_id)

        return str(result)

    # =========================================================
    # Search by team
    # =========================================================

    if (
        "search by team" in normalized
        or "search tickets assigned to" in normalized
        or "find tickets assigned to" in normalized
    ):
        team_name = _find_team_name(instruction)

        if team_name is None:
            return None

        tool = mcp_tools.get("search_by_team")

        if tool is None:
            raise RuntimeError(
                "MCP tool 'search_by_team' was not provided."
            )

        result = tool(team_name)

        return str(result)

    # =========================================================
    # Update ticket status
    # =========================================================

    if (
        "update ticket" in normalized
        and (
            "status" in normalized
            or "close ticket" in normalized
            or "set ticket" in normalized
        )
    ):
        ticket_id = _find_ticket_id(instruction)

        if ticket_id is None:
            return None

        status = None

        for candidate in ("open", "pending", "closed"):
            if candidate in normalized:
                status = candidate.capitalize()
                break

        if status is None:
            return None

        tool = mcp_tools.get("update_ticket_status")

        if tool is None:
            raise RuntimeError(
                "MCP tool 'update_ticket_status' was not provided."
            )

        result = tool(ticket_id, status)

        return str(result)

    # =========================================================
    # No deterministic MCP mapping
    # =========================================================

    return None


def _execute_single_task(
    task_id: str,
    instruction: str,
    goal: str,
    dependency_context: str,
    llm: BaseChatModel,
    mcp_tools: dict[str, Callable[..., Any]] | None,
) -> tuple[str, str]:
    """
    Execute one task.

    Tasks that clearly map to MCP operations use the real MCP tools.
    Reasoning and synthesis tasks are handled by the LLM.
    """

    if mcp_tools:
        mcp_result = execute_mcp_task(
            instruction=instruction,
            mcp_tools=mcp_tools,
        )

        if mcp_result is not None:
            return task_id, mcp_result

    prompt = f"""
Overall goal:
{goal}

Current task:
{instruction}

Prerequisite outputs:
{dependency_context}

Instructions:

- Complete only the current task.
- Use the prerequisite outputs when available.
- Reason only from supplied information.
- Do not invent ticket data.
- If information is missing, explicitly say what is missing.
- Be concrete and concise.
"""

    response = llm.invoke(
        [
            (
                "system",
                """
You are executing one validated task inside
a support-ticket task DAG.

Only perform the requested task.

Never invent:

- ticket IDs
- ticket status
- ticket priority
- team assignments
- customer information
- database results

If the task requires database information and that information was not
provided by an executed MCP operation, state that it is unavailable.
""",
            ),
            ("human", prompt),
        ],
        temperature=0.2,
    )

    content = response.content

    if not isinstance(content, str):
        raise RuntimeError(
            f"Task {task_id} returned unsupported content."
        )

    if not content.strip():
        raise RuntimeError(
            f"Task {task_id} returned an empty response."
        )

    return task_id, content.strip()


def execute_plan(
    plan: Plan,
    llm: BaseChatModel,
    mcp_tools: dict[str, Callable[..., Any]] | None = None,
    max_workers: int = 4,
) -> dict[str, str]:
    """
    Execute the validated DAG.

    Tasks in the same execution batch are executed in parallel.

    A task receives the outputs of all its dependencies.

    Deterministic retrieval/write tasks are routed to real MCP tools.
    Reasoning and synthesis tasks are handled by the LLM.
    """

    outputs: dict[str, str] = {}

    for batch in plan.execution_batches():

        futures: dict[Any, str] = {}

        worker_count = min(
            max_workers,
            max(1, len(batch)),
        )

        with ThreadPoolExecutor(
            max_workers=worker_count
        ) as pool:

            for task_id in batch:

                task = plan.task(task_id)

                dependency_context = "\n\n".join(
                    f"OUTPUT FROM {dependency}:\n{outputs[dependency]}"
                    for dependency in task.depends_on
                )

                if not dependency_context:
                    dependency_context = "No prerequisite outputs."

                future = pool.submit(
                    _execute_single_task,
                    task_id,
                    task.instruction,
                    plan.goal,
                    dependency_context,
                    llm,
                    mcp_tools,
                )

                futures[future] = task_id

            for future in as_completed(futures):

                task_id = futures[future]

                completed_task_id, result = future.result()

                if completed_task_id != task_id:
                    raise RuntimeError(
                        f"Task identity mismatch: expected {task_id}, "
                        f"received {completed_task_id}."
                    )

                outputs[task_id] = result

    return outputs


def final_output(
    plan: Plan,
    outputs: dict[str, str],
) -> str:
    """
    Return the output of the final synthesis task.

    A valid decomposition should have exactly one terminal task.
    """

    terminals = plan.terminal_tasks()

    if len(terminals) != 1:
        raise ValueError(
            "Expected exactly one terminal synthesis task, "
            f"found: {terminals}"
        )

    terminal = terminals[0]

    if terminal not in outputs:
        raise ValueError(
            f"Terminal task {terminal} has no execution output."
        )

    return outputs[terminal]

